### ISSUE TITLE
menu presentation broken on Nightly

### ISSUE THREAD

**Issue by kubrickfr** [horst3180/arc-firefox-theme#74]
With the Arc theme only, the menu (from the hamburger menu icon) has been completely broken for a week (and I can't screenshot it because it disappears when I press the key). 
Using the latest git rev.

**Comment by gyaru** [comment]
You mean like this? (tried without extensions too)
![example](https://i.imgur.com/ljLj5mP.png)

I'm having the same issue, Firefox 50.0a1.
Not really unexpected when using nightly but figured I'd at least report.

**Comment by kubrickfr** [comment]
Very similar indeed!

**Comment by p-boiko** [comment]
Confirm broken menu: http://screencloud.net/v/kW1z (and items aren't clickable)
The default theme for the contrast: http://screencloud.net/v/7fg7
My Nightly version: http://screencloud.net/v/7Lqk

**Comment by moriel5** [comment]
Same here.
Started on 50 towards the end, continues on 51.
I have to use the ordinary theme now.

**Comment by wolfland** [comment]
Me Too.. Worked fine with 50 but when Nightly upgraded to 51 yesterday the problem started. Works
with both the stock theme and developer mode but fails with Arc theme.
![screenshot-firefox51-noarc](https://cloud.githubusercontent.com/assets/8964224/17410725/f4807b58-5a42-11e6-8061-c4b8980728da.png)
![screenshot-firefox51-arctheme](https://cloud.githubusercontent.com/assets/8964224/17410727/f9329f1e-5a42-11e6-8866-bbe8c5bc0557.png)

**Comment by tiagorinaldi** [comment]
Same with Developer Edition (Aurora Channel)

**Comment by trinaldi** [comment]
Same with Developer Edition (Aurora Channel)

**Comment by moriel5** [comment]
It appears that this isn`t limited to Arc, but rather something global.
I had tried it with several complete themes, all have the same issues.
Also, this is not limited to Linux, I have run into the same issue on Windows 10.

**Comment by p-boiko** [comment]
More issues on Nightly. Since 26.08.2016 version active tab is not highlighted. I mean active tab background color is the same as inactive.

**Comment by stonehellway** [comment]
Same issue. I use the same Firefox version. Every Firefox theme is impacted.
I use the theme version 48.20160802.
Tried a fresh install of Firefox Developer edition: Same issue on Fedora 24 (xfce) and Windows 10.

![firefox developer](https://cloud.githubusercontent.com/assets/15817017/18226781/7bc73170-7211-11e6-80e7-e84443fc613d.png)

**Comment by moriel5** [comment]
Still there on Nightly 52.
As well as active tab not being highlighted, and container tabs menu broken, and downloads quick-menu looking weird (but not broken).
![screenshot from 2016-09-20 14-00-27](https://cloud.githubusercontent.com/assets/20175297/18667747/8d624e52-7f3a-11e6-8233-e6bb8fcbe8a6.png)

Currently using theme version 49.20160919.

**Comment by ghost** [comment]
Looks like Firefox beta v50 has updated past the change that causes this.

**Comment by kalentia** [comment]
Looks like Firefox beta v50 has updated past the change that causes this.

**Comment by tiagorinaldi** [comment]
Still facing this issue with Dev. Edition.

**Comment by raku-cat** [comment]
I switched from aurora to beta because of this, and now beta has updated to a point that it does this.  `firefox --version` just prints 50.0, thats about as far as I know about the specific version I'm on, I use this https://aur.archlinux.org/packages/firefox-beta-bin/

**Comment by horst3180** [comment]
Okay, I updated the theme for Firefox 50 beta (`firefox-50-beta` branch). So this should be fixed at least in the beta version. Note that Aurora and Nightly are moving targets and I simply can't support them properly.

**Comment by moriel5** [comment]
It's fine, we know.
The whole point (at least for me), aside from using the theme, is to post the possible issues ahead of time, so that you will know what to fix before the changes break the themes for the stable users.

Update: The fix did not work on 52.
The workaround for the tabs is working on 52.

**Comment by tostiheld** [comment]
I had the same issue but for me the fix worked

edit: @moriel5 this is funny, for me it's just the other way around: menu is fixed, tab highlighting is still broken

**Comment by p-boiko** [comment]
Thanks @moriel5 
Surely Nightly IS a moving target :)
I just looked a bit through the code, and could the hard selectors be the culprit? I mean like element > element > element...
Unfortunately didn't find a time to play with the selectors – the code is huge. I think there is just a bit restructured DOM tree, but element's names should retain.
By the way, can You suggest some tool to inspect the Firefox DOM tree? I tried some Inspector, suggested on a Firefox site about themes, but it doesn't seem to work with Nightly's Chrome DOM, only with web-pages, which is already built-in

**Comment by horst3180** [comment]
You can type `chrome://browser/content/browser.xul` into the adress bar and inspect it with the built in inspector (`ctrl + shift +c`). It doesn't work for the entire UI, but it's something at least.

I usually update the theme by diffing it against the unmodified upstream theme, though.

There's a fix for the recent tab breakage (https://github.com/horst3180/arc-firefox-theme/issues/85), but I havent gotten around to implementing it.

**Comment by wolfland** [comment]
The beta works for me on Nightly (52) as well.

Thanks

**Comment by p-boiko** [comment]
Thank you @horst3180 , very useful tips :)

**Comment by moriel5** [comment]
Strange, since for me it didn't work on either Arch (Antergos to be precise, however with Apricity, VeltOS, and several other repos added as well) nor Solus.

And I use the upstream (as in vanilla, binaries built by Mozilla themeselves) Nightly, since I download it directly from Mozilla.

**Comment by awalgarg** [comment]
@p-boiko

> By the way, can You suggest some tool to inspect the Firefox DOM tree?

@horst3180

> You can type chrome://browser/content/browser.xul into the adress bar and inspect it with the built in inspector (ctrl + shift +c). It doesn't work for the entire UI, but it's something at least.

For "the entire UI", you can enable browser debugging by opening devtools (F12) on any page, going to settings, and checking "Enable browser chrome and add-on debugging toolboxes" and "Enable remote debugging", and then pressing Ctrl+Alt+Shift+I. See https://developer.mozilla.org/en-US/docs/Tools/Browser_Toolbox for more info.

**Comment by bpseudopod** [comment]
Still a problem as of 2016-10-27 on Dev Edition. `firefox-developer --version` reports `Mozilla Firefox 51.0a2`.

**Comment by peronero** [comment]
Can confirm [the beta branch](https://github.com/horst3180/arc-firefox-theme/tree/firefox-50-beta) fixes this in 52.0a1 (2016-11-07).

**Comment by qazip** [comment]
I'm using Firefox beta (50) in Linux and Arc theme (Arc theme 49.20160920) it's bugged here. Even add-ons that open windows are not responding (umatrix).

![firefox_arc_theme_bug](https://cloud.githubusercontent.com/assets/16175716/20227055/90e66d52-a842-11e6-9386-9ca54a66cc6c.png)

**Comment by horst3180** [comment]
@mimf 49.20160920 is for Firefox 49. Build the theme from the `firefox-50-beta` branch to get the fix, or wait for the Firefox 50 release (tomorrow).
